import { StyleSheet, Platform } from "react-native";
import { colors } from "./colors";

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors["primary-bg"],
  },
  trendingSection: {
    paddingHorizontal: "4%",
    paddingTop: 15,
  },
  popularSection: {
    paddingHorizontal: "4%",
    paddingTop: 15,
  },
  serviceSection: {
    paddingHorizontal: "4%",
    paddingTop: 15,
  },
  textHeader: {
    fontFamily: "interBold",
    fontSize: 20,
    color: colors["font-hearder"],
    marginBottom: 10,
  },
  trendingCard: {
    width: 250,
    height: 130,
    borderRadius: 20,
    position: "relative",
  },

  trendingContainer: {
    overflow: "hidden",
    borderRadius: 10,
    width: 250,
    height: 130,
    marginRight: 20,
  },
  popularCard: {
    flexDirection: "column",
    width: 170,
    height: 250,
    marginRight: 15,
    backgroundColor: colors["card-primary"],
    borderRadius: 10,
  },
  popularPic: {
    width: "100%",
    height: 110,
    borderRadius: 10,
  },
  serviceCard: {
    backgroundColor: colors["card-secondary"],
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  serviceCardContainer: {
    width: "calc(100% - 10px)",
  },
  searchBar: {
    flexDirection: "row",
    height: 50,
    gap: 10,
    position: "fixed",
    width: "100%",
    paddingHorizontal: "4%",
    paddingVertical: 10,
    backgroundColor: colors["secondary-bg"],
    fontFamily: "interBold",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  drawerLabel: {
    fontFamily: "interBold",
  },
  scrollView: {
    flex: 1,
    top: 0,
  },
  searchBox: {
    backgroundColor: colors["text-input"],
    height: 30,
    padding: 3,
    paddingHorizontal: 10,
    flex: 1,
    borderRadius: 5,
    color: colors["font-header"],
    fontFamily: "interMedium",
    color: colors["font-hearder"],
  },
  searchButton: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    padding: 5,
    backgroundColor: colors["text-input"],
  },
  textName: {
    fontFamily: "interBold",
    fontSize: 18,
    color: colors["font-name"],
  },
  textPrice: {
    fontFamily: "interExtraBold",
    fontSize: 10,
    color: colors["font-charge"],
  },
  textProfession: {
    fontFamily: "interBold",
    fontSize: 15,
    color: colors["font-profession"],
  },
  textLocation: {
    fontFamily: "interRegular",
    fontSize: 12,
    color: colors["font-location"],
  },
  label: {
    fontFamily: "interSemiBold",
    fontSize: 18,
    color: colors["font-location"],
  },
  content: {
    fontFamily: "interSemiBold",
    fontSize: 18,
    color: colors["font-accent"],
  },
  bookingPage: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  bookingCard: {
    width: "90%",
    padding: 10,
    backgroundColor: colors["card-secondary"],
    borderRadius: 5,
    ...Platform.select({
      web: {
        boxShadow: "1px 1px 5px rgba(0, 0, 0, 0.3)",
      },
      ios: {
        shadowColor: "rgb(0,0,0)",
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  bookingDetails: {
    gap: 10,
    flexDirection: "row",
  },
  bookingCol: {
    flex: 1,
    flexDirection: "column",
    gap: 5,
  },
  bookingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bookingForm: {
    width: "100%",
    flexDirection: "column",
    gap: 10,
    marginVertical: 10,
  },
  bookingFormRow: {
    gap: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  formInput: {
    flex: 1,
    padding: 7,
    backgroundColor: colors["card-primary"],
    borderColor: colors["secondary-bg"],
    color: colors["font-charge"],
    borderWidth: 2,
    borderRadius: 5,
    fontFamily: "interMedium",
    fontSize: 12,
  },
  formInputDate: {
    padding: 7,
    backgroundColor: colors["card-primary"],
    borderColor: colors["secondary-bg"],
    color: colors["font-charge"],
    borderWidth: 2,
    borderRadius: 5,
    fontFamily: "interMedium",
    fontSize: 12,
    flex: 1,
  },
  formInputAddress: {
    height: 100,
    padding: 7,
    backgroundColor: colors["card-primary"],
    borderColor: colors["secondary-bg"],
    color: colors["font-charge"],
    borderWidth: 2,
    fontFamily: "interMedium",
    fontSize: 12,
    borderRadius: 5,
  },
  formActions: {
    gap: 5,
    marginBottom: 10,
  },
  checkoutBtnPayment: {
    padding: 7,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors["btn-primary"],
    borderRadius: 5,
  },
  checkoutBtnLater: {
    padding: 7,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors["icon-active"],
    borderRadius: 5,
  },
  checkoutBtnCoin: {
    padding: 7,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors["rating-color"],
    borderRadius: 5,
  },
  auth: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors["primary-bg"],
  },
  authCard: {
    width: "80%",
    padding: 10,
    gap: 10,
    alignItems: "center",
    backgroundColor: colors["card-secondary"],
    borderRadius: 5,
    ...Platform.select({
      web: {
        boxShadow: "1px 1px 5px rgba(0, 0, 0, 0.3)",
      },
      ios: {
        shadowColor: "rgb(0,0,0)",
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  authHeader: {
    marginBottom: 10,
    fontFamily: "interBold",
    fontSize: 20,
    color: colors["font-charge"],
  },
  formInputWrapper: {
    width: "100%",
    backgroundColor: colors["card-primary"],
    borderColor: colors["secondary-bg"],
    borderWidth: 2,
    borderRadius: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 7,
    position: "relative",
  },
  formInputWrapperError: {
    width: "100%",
    backgroundColor: "rgba(255,0,0,.1)",
    borderColor: colors["font-accent"],
    borderWidth: 2,
    borderRadius: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 7,
    position: "relative",
  },
  authFormInput: {
    width: "100%",
    padding: 7,
    color: colors["font-charge"],
    fontFamily: "interMedium",
    fontSize: 16,
  },
  disabledAuthFormInput: {
    width: "100%",
    padding: 7,
    color: colors["font-charge"],
    fontFamily: "interMedium",
    fontSize: 16,
    opacity: 0.7,
  },
  authForminputError: {
    width: "100%",
    padding: 7,
    color: colors["font-accent"],
    fontFamily: "interMedium",
    fontSize: 16,
  },
  errorText: {
    alignSelf: "flex-start",
    fontFamily: "interBold",
    color: colors["font-accent"],
    fontSize: 12,
    marginBottom: -5,
  },
  showPassArea: {
    position: "absolute",
    right: 0,
    height: "100%",
    paddingHorizontal: 7,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 111111,
  },
  authBtn: {
    padding: 7,
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors["btn-primary"],
    borderRadius: 5,
  },
  toggleAuthSection: {
    flexDirection: "row",
    gap: 5,
  },
  toggleAuthQuery: {
    color: colors["font-name"],
    fontFamily: "interMedium",
    marginBottom: 10,
  },
  toggleAuth: {
    color: colors["font-link"],
    fontFamily: "interSemiBold",
  },
  on: {
    display: "flex",
    zIndex: 11111111,
  },
  off: {
    display: "none",
    zIndex: 11111111,
  },
  walletFont: {
    fontFamily: "interSemiBold",
    marginBottom: 10,
  },
  good: {
    color: colors["font-recommendation"],
    fontFamily: "interBold",
    marginHorizontal: 10,
  },
  low: {
    color: colors["font-accent"],
    fontFamily: "interBold",
    marginHorizontal: 10,
  },
  wallet: {
    padding: 20,
    display: "flex",
    alignItems: "center",
  },
  rechargeWallet: {
    padding: 10,
    borderRadius: 5,
    backgroundColor: colors["secondary-bg"],
  },
  rechargetext: {
    fontFamily: "interBold",
    color: colors["primary-bg"],
  },
  packageContainer: {
    flexDirection: "column",
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  packageCard: {
    padding: 10,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 5,
    borderWidth: 1,
    borderColor: colors["secondary-bg"],
    borderStyle: "dashed",
    borderRadius: 7,
    backgroundColor: colors["card-bio"],
    marginBottom: 10,
  },
  coins: {
    fontFamily: "interBold",
    color: colors["font-charge"],
    fontSize: 20,
  },
  price: {
    fontFamily: "interSemiBold",
    color: colors["font-charge"],
    fontSize: 18,
  },
  span: {
    color: colors["font-accent"],
  },
  purchase: {
    padding: 7,
    border: "none",
    cursor: "pointer",
    backgroundColor: colors["secondary-bg"],
    borderRadius: 3,
    color: colors["primary-bg"],
    fontFamily: "interMedium",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    margin: 20,
  },
  input: {
    backgroundColor: "#efefefef",
    borderRadius: 8,
    fontSize: 20,
    height: 50,
    padding: 10,
  },
  cardContainer: {
    height: 50,
    marginVertical: 10,
  },
});
